platform :ios, '13.0'

target 'PulseIOSExample' do
  use_frameworks!

  pod 'PulseKit', :path => '../../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['OpenTelemetry-Swift-Api', 'OpenTelemetry-Swift-Sdk', 'SwiftProtobuf', 'KSCrash'].include?(target.name)
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
